development:
  adapter: postgresql
  encoding: unicode
  database: reading_tutor_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: reading_tutor_test
  pool: 5
  host: localhost
